### PR TITLE
#61 Added fsevents to dev dependencies for MacOS

### PR DESCRIPTION
**Pull request by Spechal**

### CODE REVIEW

**Comment by Spechal** [comment]
RFC or Approval to merge

**Comment by galbwe** [comment]
@Spechal I apologize for taking so long to get to this. I had a particularly busy workweek and a friend in town over the weekend to entertain. Do you have steps to reproduce the error or the error message itself? Thanks.

@ASTPMeetup would you please verify this on your macbook?

**Comment by Spechal** [comment]
```
$> npm install

> fsevents@1.2.7 install /Users/tcrowder/Documents/repos/codeforkansascity/meep/frontend/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download
........
../fsevents.cc:76:58: error: expected ';' after top level declarator
void FSEvents::Initialize(v8::Handle<v8::Object> exports) {
                                                         ^
                                                         ;
22 warnings and 11 errors generated.
22 warnings and 11 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1make:
*** [Release/obj.target/fse/fsevents.o] Error 1
gypgyp  ERR! ERR!build error
build error
gyp ERR! stack Error: `make` failed with exit code: 2
gypgyp ERR!  stackERR!      at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gypstack  Error: `make` failed with exit code: 2
ERR!gyp  stackERR!     at ChildProcess.emit (events.js:196:13)
 gypstack      at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
ERR! gyp stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/12.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/tcrowder/Documents/repos/codeforkansascity/meep/frontend/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/tcrowder/Documents/repos/codeforkansascity/meep/frontend/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64" "--napi_version=4" "--node_abi_napi=napi"
gyp ERR!gyp  cwdERR! /Users/tcrowder/Documents/repos/codeforkansascity/meep/frontend/node_modules/fsevents
 Systemgyp Darwin 18.6.0
 ERR! node -vgyp v12.1.0
 gypERR!  ERR!command  "/usr/local/Cellar/node/12.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/tcrowder/Documents/repos/codeforkansascity/meep/frontend/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/tcrowder/Documents/repos/codeforkansascity/meep/frontend/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64" "--napi_version=4" "--node_abi_napi=napi"
node-gyp -v v3.8.0
gyp ERR!gyp  cwdERR!  /Users/tcrowder/Documents/repos/codeforkansascity/meep/frontend/node_modules/fsevents
not okgyp
 ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/12.1.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/tcrowder/Documents/repos/codeforkansascity/meep/frontend/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/tcrowder/Documents/repos/codeforkansascity/meep/frontend/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/tcrowder/Documents/repos/codeforkansascity/meep/frontend/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1000:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)
node-pre-gyp ERR! System Darwin 18.6.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/12.1.0/bin/node" "/Users/tcrowder/Documents/repos/codeforkansascity/meep/frontend/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/tcrowder/Documents/repos/codeforkansascity/meep/frontend/node_modules/fsevents
node-pre-gyp ERR! node -v v12.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/12.1.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/tcrowder/Documents/repos/codeforkansascity/meep/frontend/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/tcrowder/Documents/repos/codeforkansascity/meep/frontend/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)
```

**Comment by Spechal** [comment]
Closing in favor of #67

**Pull request closed without merging**
